### ISSUE TITLE
ios 9.3.5?

### ISSUE THREAD

**Issue by nmjohnson** [Mr-Bossman/CCminer-IOS#2]
How would I go about compiling this for ios 9.3.5?

**Comment by Mr-Bossman** [comment]
While it is possible to force build this for 9.x this isn't a good idea. This should work on ios 10.x and if you can update your phone it should work fine. If you can't update your phone it's because it's an older iPhone like the 4s which can't possibly run this software. All the devices that are End Of Life in 9.x can't run this software even if it was installed. https://en.m.wikipedia.org/wiki/IOS_version_history

I set the minimum architecture to match the requirements of ccminer, and xcode also added a 10.x minimum because all devices thar have 10.x meet the requirements.
